import * as React from "react"

import {NotebookLayout} from "./layout"

import { observer } from "mobx-react"

export const NotebookView = observer((props: any) => {
  return (
    <React.Fragment>
      <NotebookLayout>
       <div>
       {"hi - click ^^ the canvas icon above to change the theme"}
       <br/>
       {"the first icon on the left <<- over there will nav u to the 'themePrimary' generated by office fabric loadThemes()"}
       </div>

      </NotebookLayout>
    </React.Fragment>
  )
})
